### ISSUE TITLE
High CPU load and frequent reload of Gmail page after recent update

### ISSUE THREAD

**Issue by michal7918** [Ayce45/gmail-pop3-auto-refresh#1]
Since recent update (v1.2) I noticed increased CPU load caused by chrome process. After some observation, I found that extension's target Account and import page is frequently fully reloaded (like if F5 is pressed). This is not happening with version 1.0 to which I reverted. Hard to say if reload of Account and import page is the cause of increased load or consequence of other problem in script.

System: Ubuntu 20.04, Chromium 96, Chrome 96

In any case, thank you for very useful extension!

**Comment by Ayce45** [comment]
Thank you for your issue.

Yes, I add in 1.2 version reload page every minute, It's true that I didn't think that it could cause a loss of performance...
I change that it to every hour in 1.3.

With pleasure, if you want to help me to promote my extension do not hesitate to note the extension on the Chrome web store and to leave a nice comment 😁

**Comment by michal7918** [comment]
Thank you, sure I'll add review on Chrome webstore, praise is deserved. 

I would not say that performance was issue but increased load and temperature was quite noticable on simple home server where I run it.

Thanks for quickly patching the issue. Just out of curiosity, what is the reason for page reloading? I was runnig v1.0 several days without break and did not notice any issues...

**Comment by Ayce45** [comment]
Some people say, after 1 hour not all pop3 account are refresh, I don't know why. With refresh the issus is fixed.
