### ISSUE TITLE
Port to Firefox add-on

### ISSUE THREAD

**Issue by OHRassi** [Ayce45/gmail-pop3-auto-refresh#4]
Would you be willing/able to convert this to a Firefox add-on?  There is nothing like it for Firefox, and it would be great to have it.

Thank you!

**Comment by Ayce45** [comment]
https://gist.github.com/Ayce45/4e8bbf6c1c3e3b07d3c5af891ad4a7bb

It's simple you need to install the extension Tampermonkey in Firebox and click to "add new script" and paste the body.

Open the good URL like with the chrome extension and it's work.

**Comment by OHRassi** [comment]
Thank you!

**Comment by Ayce45** [comment]
I add Firefox with extension now: https://addons.mozilla.org/fr/firefox/addon/gmail-pop3-auto-refresh/
