### ISSUE TITLE
[Feature]: Can this work on gmail account apart from the one you are signed in on in your Chrome profile?

### ISSUE THREAD

**Issue by ghost** [Ayce45/gmail-pop3-auto-refresh#5]
### Is your feature request related to an issue? Please describe.

I use my personal Google account to sign into my Chrome profile. For that, my personal email is mail.google.com/mail/u/**0**/
However, I often check my work Gmail account in the same browser, and don't want to have to switch to a new profile. <y work email is mail.google.com/mail/u/**1**/

This extension seems to only check mail.google.com/mail/u/**0**/

### Describe the solution you'd like

Is there a way for it to check other Gmail accounts you have open in your browser?

**Comment by Ayce45** [comment]
Hi @ayohwife,
I try with mail.google.com/mail/u/1/ and it works!

You can check in Chrome DevTools → Console, if you have "[Gmail POP3 Auto Refresh] Refresh Pop", the extension refreshes your pop3 account.

You can also click "View History" on any of your POP3 addresses to see all the refreshes.
