### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by cbnsingram** [Ayce45/gmail-pop3-auto-refresh#6]
### Description of the bug

Not refreshing on schedule

### Steps To Reproduce

Wait - it eventually stops refreshing.  Not sure yet if related to sleep mode or browser closer. 

### Expected Behaviour

Should refresh every 2 minutes I believe.

### Additional Information

I am not keeping the extra tab up that opens when I click the extension.  Is that supposed to stay up for this to work?

**Comment by cveld** [comment]
@cbnsingram can you change the title in something appropriate?

**Comment by Ayce45** [comment]
Disabled sleep mode for Gmail tab
